[package]
name = "minici"
version = "0.1.0"
edition = "2021"
authors = [
    "Oguzhan Ozdemir <oguzhan.ozdemir@thundra.io"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
dialoguer = "0.9.0"
dirs = "4.0.0"
getopts = "0.2.21"
handlebars = "4.1.3"
pager = "0.16.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
serde_yaml = "0.8.21"
